```{r}
library(dplyr)
library(ggplot2)
library(scales)
```

```{r}
source("src/loading_data.R")
```

```{r}
summary(dataObs)
```
# Étude descriptive


## Variables explicatives

```{r}
summVarsExp <- dataObs %>% 
  mutate_if(is.factor, function(v) as.integer(v) - 1L) %>% 
  group_by(group) %>% 
  select(-RE78) %>% 
  summarise(n = n(), across(everything(), mean)) %>% 
  select(-group) %>% 
  t()

colnames(summVarsExp) <- c("Control", "Treated")

summVarsExp <- round(summVarsExp, 4L)
summVarsExp

conversion_latex(summVarsExp, nom = "data_vars_exp")
```
```{r}
dataObs %>% 
  ggplot() +
  geom_histogram(aes(x = education, 
                     y = after_stat(ncount / sum(ncount)), colour = group)) +
  ggtitle("Distribution de la variable education en fonction du groupe") +
   scale_y_continuous(labels = scales::percent_format()) +
  ylab("Proportion")
```
```{r}
dataObs %>%
  dplyr::count(education, group)  %>%
  group_by(group) %>%
  mutate(Proportion = n / sum(n)) %>%
  ggplot() + 
  geom_col(aes(education, Proportion, fill = group), position = 'dodge') +
  ggtitle("Distribution de la variable education en fonction du groupe")
```

```{r}
table(dataObs$group, dataObs$Black)
```

```{r}
table(dataObs$group, dataObs$married)
```

```{r}
table(dataObs$group, dataObs$nodegree)
```

```{r}
dataObs %>% 
  ggplot() +
  geom_density(aes(x = RE74, colour = group)) +
  ggtitle("Distribution de RE74, en fonction du groupe")
```

```{r}
table(dataObs$group, dataObs$indRE74)
```

```{r}
dataObs %>% 
  ggplot() +
  geom_density(aes(x = RE75, colour = group)) +
  ggtitle("Distribution de RE74, en fonction du groupe")
```

```{r}
table(dataObs$group, dataObs$indRE75)
```


## Contrefactuels

```{r}
summary(dataObs$RE78)
```

```{r}
dataObs %>% filter(group == "Control") %>% select(RE78) %>% summary()
```
```{r}
dataObs %>% filter(group == "Treated") %>% select(RE78) %>% summary()
```
Proportion de 0 par groupe
```{r}
dataObs %>% 
  group_by(group) %>% 
  summarise(propZero = sum(RE78 == 0.0) / n())
```

```{r}
dataObs %>% 
  ggplot() +
  geom_density(aes(x = RE78)) +
  ggtitle("Distribution de RE78 sur l'ensemble de l'échantillon")
```

```{r}
dataObs %>% 
  ggplot() +
  geom_density(aes(x = RE78, colour = group)) +
  ggtitle("Distribution de RE78, en fonction du groupe")
```

```{r}
ks.test(pull(dataObs[dataObs$group == "Control", "RE78"]), 
        pull(dataObs[dataObs$group == "Treated", "RE78"]))
```


## Score de propension

```{r}
source("src/calcul_propension.R")
```

```{r}
dataProp <- dataObs %>% 
  select(group) %>% 
  mutate(e = propValues)

dataProp %>% filter(group == "Treated") %>% 
  ggplot() + 
  geom_density(aes(x = e)) +
  ggtitle("Score de propension (estimé) chez les traités")
```

```{r}
dataProp %>% filter(group == "Control") %>% 
  ggplot() + 
  geom_histogram(aes(x = e)) +
  ggtitle("Score de propension (estimé) pour le groupe contrôle")
```

```{r}
ggplot(dataProp) + 
  geom_histogram(aes(x = e, colour = group)) 
```


```{r}
dataProp %>% 
  filter(group == "Treated") %>% 
  ggplot() + geom_histogram(aes(x = e))
```

```{r}
dataProp %>% filter(group == "Control") %>% select(e) %>% summary()
dataProp %>% filter(group == "Treated") %>% select(e) %>% summary()
```

```{r}
dataProp %>% 
  group_by(group) %>% 
  summarise(n = n(), mean_e = mean(e))
```
